### ISSUE TITLE
license is missing

### ISSUE THREAD

**Issue by zmt** [GraysonMartin/WebBuzzer#1]
I am new to firebase, but got it working in my dev. environment. I might want to hack it a bit for my needs. I plan to use this to run a custom jeopardy game for an employee resource group at a private event. 

I note the
```
  <footer>&copy; 2017 Grayson Martin</footer>
```
in the html, but I don't see any indication of the form of license. Do you intend to use an MIT license, GPLv2, or what?

**Comment by gm3197** [comment]
Sorry about forgetting to mention it in the README. I didn't include a license on purpose. You can read more about it here: https://choosealicense.com/no-license/ I specifically mean this line: "Unless you include a license that specifies otherwise, nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation."

If you wish to use this for your employee resource group, then you may use it here: http://graysonmartin.net/buzz
